let example = `>gi|769980658|ref|WP_045096643.1| hypothetical protein [Legionella fallonii]
--------------------------------------------------------MNYK
ITEHY-ARGEEKFIAEFNELNDARFFMTKKSSIDDVERKKVIYRLYDDH-ELLHELNKEN
ISITHAKYAEGNGDFNNAVPFIFQVMIKTMDSLERKTIAQFNDKNDANLFVVCKFEDDNT
VHDNDLFLIFKD-KILIDTVNKTITANRKKESSGSSGNEKG-STYKLSPLSTRPTPGGGP
ADYW--VKNEDE--------
>gi|966500986|ref|WP_058517659.1| hypothetical protein [Legionella parisiensis]
--------------------------------------------------------MRYK
ITEQF-ARGEEKVIAEFNEFKDTHIFIAKKAANADLEKQKIIFRLYDDS-DLLHQINREN
ISVSYAKYAEGNGDL-NLIQFPFHAMIKTQNALKKRAIANFNDKNDANLFIISKCESDES
VQDNDLFFLFKE-RTLIDTLSRIINTHREKEATRSIRNGQG-AKFHPTPMPRRPIPPGVP
SDCW--IEKDDDNQ------
>gi|966468150|ref|WP_058499476.1| hypothetical protein [Legionella gratiana]
--------------------------------------------------------MRYK
VSEQF-ARGEEKAIAEFKELNDAKIFIAQKQEDTRIEKQKIIFRLYDDF-DLLHEFNEDN
ISVSYAKYADGNGEL-NIIKFPFHVMIKAQHATDKKCIANFNHRINANLFVISKCNLDDL
LNENDLFFIFKD-QNLIDTLNKIICTHRKTESSRMQRTEKG-AKFHPTPLPTRPIPTGGP
SDCW--IEENNEHE------
>gi|518063686|ref|WP_019233894.1| hypothetical protein [Legionella anisa]
--------------------------------------------------------MRYK
ITEQF-ARGEEKVIADFSELNDTHIFLAKKSANADLEKQKIIFRLYDNS-DLLHEINRET
ISVAHANYAEGNGDL-YLIQLPFHVMFKAQDVLEKREIANFNDKNDANLFIIGKCESDES
IQDNDLFFLFKE-QNLIDTLTRIINTHREKEATRTTKNEKG-AKFHPTPMSRRPIPPGGP
SDCW--VEEDDDNPQ-----
>gi|966416949|ref|WP_058460234.1| hypothetical protein [Fluoribacter bozemanae]
--------------------------------------------------------MRYK
ITEQF-ARGEEKVIAEFSELNDTRIFLAQKSANADLEKQKIIFRLYDDS-DLLHEINREN
ISVAYAKYAEGNGDI-NLIQFPYHTMIKTQKALEKRRIANFNDKNDANLFIISKCESDES
IQDNDLFFLFKE-HTLIDTLSRIINAHREKEATRIARNEKG-AKFHPTPMPRRPIPPGLL
NDCW--IEEDDNDN------
>gi|966458951|ref|WP_058491734.1| hypothetical protein [Legionella worsleiensis]
--------------------------------------------------------MNYK
ITEHY-ARGEEKPIAEFNDLNEAKLFLAKKSSITDEERKKVIYRLYDDH-ELLHELNKES
ISITHAKYAEGNGDFNNAAPFIFQVMIKTMDSLERKTIAQFNDKNDANLFVVCKFEDDNT
VHDNDLFLIFKD-KILIDTVNKTIIANRKKESSGSSGNEKG-STYKLSPLSTRPTPSGGP
ADYW--VKNEDDDENIK---
>gi|1590807530|ref|WP_131779176.1| hypothetical protein [Fluoribacter bozemanae]
--------------------------------------------------------MRYK
ITEQF-ARGEEKVIAEFSELNDTRIFLAQKSANADLEKQKIIFRLYDDS-DLLHEINREN
ISVAYAKYAEGNGDI-NLIQFPYHAMIKTQKALEKRRIANFNDKNDANLFIISKCESDES
IQDNDLFFLFKE-HTLIDTLSRIINTHREKEATRITRNEKG-AKFHPTPMPRRPIPPGLL
NDCW--IEEDDNDN------
>gi|966504452|ref|WP_058521111.1| hypothetical protein [Legionella tucsonensis]
--------------------------------------------------------MRYK
ITEQF-ARSEEKVIAEFNELNDARIFLTKKSANADLEKQKIIFRLYDDF-DLLHEINREH
ISVAYAKYAEGNGDP-NLIQLSFHVMIKIQKALEKRGIANFNDKNDANLFIISKCKSDES
IQDNDLFFLYKG-QNLIDTLTRIINTHREKEAARISRNEKG-AKFHPTPMPRRPVPPGLL
NDCW--VEEDNDDDQ-----
>gi|962205598|gb|KTC90535.1| hypothetical protein Ldum_1603 [Fluoribacter dumoffii NY 23]
--------------------------------MRP-------------GDLAALVMMQYK
VTAQF-ARGEERIIAELAEVNDARLFIAKKSEKSALEKQNIIYRLYEDS-DLLEEFNKEH
LSVAYAKYAEGNGDL-NLVQLPFQLMFKPVNFPEKKEIARFDDKNDANLFVISKCESDDA
LHDQDLFFLFKN-RSLMETLNRVISSQRKKEVIDDARSGKG-AKFHPTPLPNRPTPSGGP
PDCW--IEEDNDK-------
>gi|769980272|ref|WP_045096257.1| hypothetical protein [Legionella fallonii]
--------------------------------------------------------MNFK
ITEHY-ARGEEKFIAEFNELNDAKFFMSKKSSIDDVERKNVIYRLYDDH-ELLHELNKEN
ISITHAKYAEGNGDFNNAAPFIFQVVIKTMDSLERKTIAQFNDKNDAYLFVVCKFEHDNT
IHDNDLLLILRD-KILIDTANKTIIANRKKESSGSSGNEKG-STYKLSPLSTRPTPGGGP
ADYW--VKNEDEDE------
>gi|1593600230|ref|WP_133137202.1| hypothetical protein [Legionella rowbothamii]
--------------------------------------------------------MNFK
ITEHY-ARGEEKLIAEFNELNDAKFFMTKKSSINDVERKKVIYRLYDDH-ELLHELNNEN
ISITHAKYAEGNGDFNNAAPFIFQVMIKTLDSLERKTIAQFNDKNDAILFVACKFENDNT
MHDNDLLLIFKD-KISIDTVNKTIIANRKNESSGSSGNEKG-STYKLSPLSTRPTPGGGP
ADYW--VKNEDEDE------
>gi|966435813|ref|WP_058476193.1| hypothetical protein [Legionella steigerwaltii]
--------------------------------------------------------MQYK
ITEQF-ARGEEKVIAEFNEFSDTKLFITKKIANSDQEKQKIIYRLYDDS-DLLHELNKEN
ISVAYAKYAEGNGDL-NLIQLPFLLMSKQENLQAKREIARFAEQNDANLFMMTKCETDTT
TQDNDLFFLFKN-QSLIDTLNRVINSHRQKEAVRFTGNEKG-ATFHPTPLPNRPTPPGGP
SDCW--IENDEDK-------
>gi|518179867|ref|WP_019350075.1| hypothetical protein [Fluoribacter dumoffii]
--------------------------------------------------------MQYK
VTAQF-ARGEERIIAELAEVNDARLFIAKKSEKSALEKQNIIYRLYEDS-DLLEEFNKEH
LSVAYAKYAEGNGDL-NLVQLPFQLMFKPVNFPEKKEIARFDDKNDANLFVISKCESDDA
LHDQDLFFLFKN-RSLMETLNRVISSQRKKEVIDDARSGKG-AKFHPTPLPNRPTPSGGP
PDCW--IEEDNDK-------
>gi|653019195|ref|WP_027271148.1| hypothetical protein [Legionella sainthelensi]
--------------------------------------------------------MHYK
VSEQF-ARGEEKAIAEFKELNDAKIFIAQKQENTRIEKQKIIFRLYDDC-DLLHEFNEYN
STVAYAKYADGNGDF-NIIKFPYHVMIKAPHATDKKCIANFIHKINANLFVISKCNRDAL
LNENDLFFIFKE-QNLIDTLNKIICTHRKTKSERTDDNGKG-AKFHPSPLPKRPIPPGGP
SDCW--IEENNEDES-----
>gi|489731807|ref|WP_003635923.1| hypothetical protein [Legionella longbeachae]
--------------------------------------------------------MRYK
VTEQF-ARGEEKAIAEFRELSDAKIFIDQKQENTRIETQKIIFRLFDDF-DLLHEFNENN
SSVAYAKYADGNGDL-NIIKLPYHVMIKAQHATDKKCIANFIDKINANLFVISKCDNDDA
VDENDLFFIFKE-QNLIDTLNKILCIHRKIKSDRSKENERG-AKFHPTPLSRRPTPPGGP
SDCW--IEENNENE------
>gi|1445093916|ref|WP_115702212.1| hypothetical protein [Legionella sp. 13.8642]
--------------------------------------------------------MRYK
VSEQF-ARGEEKAIAEFKEFNDAKIFIAQKQENTQIEKQKIIFRLYDDC-DLLHEFNEYN
STVAYAKYADGNGDF-NIIKFPYHVMIKAQHATDKKCIANFIHKINANLFVISKCNRDAL
LNENDLFFIFKE-QNLIDTLNKIICIHRKTKSERTDDNEKG-AKFHPSPLPKRPTPPGGP
SDCW--IEKNNEDES-----
>gi|1558249191|ref|WP_128130126.1| hypothetical protein [Legionella sainthelensi]
--------------------------------------------------------MRYK
VSEQF-ARGEEKAIAEFKEFNDAKIFIAQKQENTQIEKQKIIFRLYDDC-DLLHEFNEYN
STVAYAKYADGNGDF-NIIKFPYHVMIKAQHATDKKCIANFIHKINANLFVISKCNRDAL
LNENDLFFIFKE-QNLIDTLNKIICIHRKTKSDRTDDNEKG-AKFHPSPLPKRPTPPGGP
SDCW--IEKNNEDES-----
>gi|1326066211|ref|WP_101901128.1| hypothetical protein [Legionella sainthelensi]
--------------------------------------------------------MRYK
VSEQF-ARGEEKAIAEFKEFNDAKIFIAQKQENTQIEKQKIIFRLYDDC-DLLHEFNEYN
STVAYAKYADGNGDF-NIIKFPYHVMIKAQHATDKKCIANFIHKINANLFVISKCNFDAL
LNENDLFFIFKE-QNLIDTLNKIICIHRKTKSDRTDDNEKG-TKFHPSPLPKRPTPPGGP
SDCW--IEENNEDES-----
>gi|1445100194|ref|WP_115707795.1| hypothetical protein [Legionella sp. 13.8642]
--------------------------------------------------------MRYK
ISEQF-ARGEEKAIAEFKEFNDAKIFIDQKQENTQIEKQKIIFRLYDDC-DLLHEFNEYN
STVAYAKYADGNGDF-NIIKFPYHVMIKAQHATDKKCIANFIHKINANLFVISKCNRDAL
LNENDLFFIFKE-QNLIDTLNKIICIHRKTKSDRTDDNEKG-AKFHPSPLPKRPIPPGGP
SDCW--IEENNGDES-----
>gi|1437642139|emb|STX44944.1| Uncharacterised protein [Legionella donaldsonii]
--------------------------------MPELLNFLDGAIYPIINGYVFGNQMRYK
ITEHY-ARGEEKLIAAFNKFNEARLFMAQKASIDEEAKKKIIYRLYDDN-ELLHELNKTN
ISITHAHYAEGNGDLNNAAPFIFQVMAKTAESLEKEMIAQFNDKKDAKLFVVCKIETDQT
IHDSDLFFIVKG-NLLIDTANKIIIANRNKEASRASGNEKN-PT--LNPLPTRPTPRGGP
PDYW--VDKRDDDEKGN---
>gi|962195207|gb|KTC80268.1| hypothetical protein Lche_2288 [Legionella cherrii]
-------------------------------------------------------MMRYK
ITEQF-ARGEEKFIAEFDELKNINLFLTKKVANSDQEKQKIIYRIYDDS-DLLHVLNNEN
VSVAYAKYAEGNGDL-NIIQLPFMVLIKPENVQEKSEIARFSEKIDADSFIEDKCELDET
VQDNDLFFLFKN-QNLIDTLNRVINSHRKKEAIRFTENEQG-AKFHPSPLPNRPKPPGGP
SDCW--IEEDENN-------
>gi|963704393|ref|WP_058388292.1| hypothetical protein [Legionella cherrii]
--------------------------------------------------------MRYK
ITEQF-ARGEEKFIAEFDELKNINLFLTKKVANSDQEKQKIIYRIYDDS-DLLHVLNNEN
VSVAYAKYAEGNGDL-NIIQLPFMVLIKPENVQEKSEIARFSEKIDADSFIEDKCELDET
VQDNDLFFLFKN-QNLIDTLNRVINSHRKKEAIRFTENEQG-AKFHPSPLPNRPKPPGGP
SDCW--IEEDENN-------
>gi|966401982|ref|WP_058445577.1| hypothetical protein [Legionella feeleii]
--------------------------------------------------------MRYK
ITEHY-ARGEEKLIAAFNKLNEARLFMAQKASIDEEAQKKIIYRLYDNN-ELLHELNQTN
ISITHAQYAEGNGDLNNAAPFIFQVMVKTTESLEKETIAQFNDKNDAKLFVACKIETDKT
IRDSDLFFTFKE-NMLIDTANKIIIAHRQKECSRAGGNKKS-PT--LNPLPTRPTPGGGP
PDYW--VDKSDDDENGK---
>gi|1442545687|ref|WP_115176126.1| hypothetical protein [Legionella feeleii]
--------------------------------------------------------MRYK
ITEHY-ARGEEKLIAAFNKLNEARLFMAQKASIDEEAQKKIIYRLYDDN-ELLLELNQTN
ISITHAQYAEGNGDLNNAAPFIFQVMVKTTESLEKEIIAQFNDKNDAKLFVACKIETDKT
IRDSDLFFTFKE-NMLIDTANKIIIAHRQKECSRAGGNKKS-PT--LNPLPTRPTPGGGP
PDYW--VDKSDDDENGK---
>gi|1442913774|ref|WP_115222792.1| hypothetical protein [Legionella donaldsonii]
--------------------------------------------------------MRYK
ITEHY-ARGEEKLIAAFNKFNEARLFMAQKASIDEEAKKKIIYRLYDDN-ELLHELNKTN
ISITHAHYAEGNGDLNNAAPFIFQVMAKTAESLEKEMIAQFNDKKDAKLFVVCKIETDQT
IHDSDLFFIVKG-NLLIDTANKIIIANRNKEASRASGNEKN-PT--LNPLPTRPTPRGGP
PDYW--VDKRDDDEKGN---
>gi|671588769|ref|WP_031564709.1| hypothetical protein [Legionella wadsworthii]
--------------------------------------------------------MQYK
ITEQF-ARGEEKAIAEFYDLYDSRIFLAQKIADADLEKQKIIFRVYDDS-ELVHESNRAH
ISISYAKYAEGNGDL-ALAQLPIHLMIQSTPSTQKINIANFHIRNDAYLFVTQKCELDDR
IKDNTLFFIYQE-KNLIDTVSKTVVINRKKEAARYTRNENK-AVFHPTPLSIRPKPPGGP
SYCW--IEEDDEN-------
>gi|1539467649|emb|VEB38802.1| Uncharacterised protein [Legionella cherrii]
-------------------------------------------------------MMRYK
ITEQF-ARGEEKFIAEFDELKNINLFLTKKVANSDQEKQKIIYRIYDDS-DLLQVLNNEN
VSVAYAKYAEGNGDL-NIIQLPFMVLIKPENVQEKSEIARFSEKIDADSFIEDKCELDET
VQDNDLFFLFKN-QNLIDTSNRVINSHRKKEAIRFTENEQG-AKFHPSPLPNRPKPPGGP
SDCW--IEEDENN-------
>gi|654929607|ref|WP_028379977.1| hypothetical protein [Legionella cherrii]
--------------------------------------------------------MRYK
ITEQF-ARGEEKFIAEFDELKNINLFLTKKVANSDQEKQKIIYRIYDDS-DLLQVLNNEN
VSVAYAKYAEGNGDL-NIIQLPFMVLIKPENVQEKSEIARFSEKIDADSFIEDKCELDET
VQDNDLFFLFKN-QNLIDTSNRVINSHRKKEAIRFTENEQG-AKFHPSPLPNRPKPPGGP
SDCW--IEEDENN-------
>gi|966441216|ref|WP_058481539.1| hypothetical protein [Legionella waltersii]
--------------------------------------------------------MNFK
ITEHY-ARGEEKFIAEFNELNDAKFFMSKKSSIDDVERKKVIYRLYDDH-ELLHELNKEN
ISITHAKYAEGNGDFNNAAPFIFQVMIKTMDSLERKTIAQFNDKNDAYLFVVCKFEHDNT
IHDNDLLLILKD-KILIDTANKTIIANRKKESSGSSGNEKG-STYKLSPLSTRPTPGGGP
ADYW--VKNEDEDE------
>gi|518045214|ref|WP_019215422.1| hypothetical protein [Legionella tunisiensis]
--------------------------------------------------------MRYK
ITEHY-ARGEEKLIAEFHELNEARFFIAKKPLLMRK-QEKIIYRLYDDN-ELLHELNKAS
ISITHASYAEGNSDFNNAAPLIFQVMVKTMNSLEKEIIAQFHDKHDAKLFIECKIEVDQT
IHDGDLFFIFKN-KILIDTANKIIIANRKKEAARSAGNEKS-RT--LSPLPTRPTPSGGP
PDYW--VDKRDDDEHGK---
>gi|1443030937|ref|WP_115301052.1| hypothetical protein [Legionella taurinensis]
--------------------------------------------------------MNFK
ITEHY-ARGEEKLIAECDELNDAKFFMSEKSSIDDMERKKVIYRLYDDH-ELLHELNKEN
ISITHAKYAEGNGDFNNATPFIFQVMIKTMDSLERKTIAQFNDKNDAYLFVVCKFEHDNR
IQDNDLLLILKD-KILIDTANKTIFANRKKESSGSSGNEKG-STYKLSPLSTRPTPGGGP
ADYW--VKNEDEDE------
>gi|966422172|ref|WP_058465373.1| hypothetical protein [Legionella cincinnatiensis]
--------------------------------------------------------MRYK
VSEQF-ARGEEKAIAEFRELSDAKIFIAQKQENTRIEKQKIIFRLYDDS-DLLHEFNENN
SSVAYAKYADGNGDL-NIIKFPYHVMIKAQHATDKKCIANFIHKINANLFVISKCDSDDQ
LNENDLFFIFKE-QNLIDTLNKIICTHRKIESDRSNDNEKG-AKFHPTPLPKRPRPPGGP
SDCW--IEENNENE------
>gi|1580563015|gb|TAL59901.1| hypothetical protein EPN84_10375 [Legionella sp.]
--------------------------------MAP--NRKDG-----IDNHNLLENMNYY
LTEHY-ARGEEKPIAAFIELGDAQLCMEKKSSTDVEEGKKVIYRLYNDH-ELLHQLNVEN
ISTSHANYAEGNGDFNSDT-FTFQIMMRTINSLEQKSVAQFNHEHDAYLFIASKFEEDTT
INENDLFLLFKN-NSLIDTLNKTIIENRNKESSRT--NQKE-ATYKLSPLSTRPTPGGGP
ADYW--VKDEDE--------
>gi|966472959|ref|WP_058503720.1| hypothetical protein [Legionella nautarum]
--------------------------------------------------------MNYK
ITEHY-ERGEEKLLASFNKLNDARLFMTKKSSIDEE-EKKIIYRVYDDQDELLLELNNEN
IFVTHAKYAEGNGDLNNTASFIFQVMIKPLGALERKEIAQFSDKNDAHLFIACKFEADNP
THDNDLFFIFKN-KILIDTLNKTIYENRKREGQKSSNNGKG-SAYRLSPLSTRPTPSGGP
PDYW--VENGDEVE------
>gi|966440606|ref|WP_058480929.1| hypothetical protein [Legionella waltersii]
--------------------------------------------------------MNYI
VTQQY-ARGEEKPIAAFNDLNEAMLFLTKKSSKDDEESKKIIYRLFDDQ-GLRFELNEEN
ISISNAKYADANGDFTYPIPFIFQVMIQTNLGSERTMVAQFNDVNDAKLFVLCQFEFNKT
IHDNDLFLIFKG-KVLIDSANKTIIANRKKESSGTGSN------YTLSPLSTRPTPGGGP
ADYW--VENREDDENSQ---
>gi|769980206|ref|WP_045096191.1| hypothetical protein [Legionella fallonii]
--------------------------------------------------------MQYR
VTEHY-ARGEEKLIAEFSELPDTKIFTAEKLALAAIDRKKLIYRIYDDA-ELLHEFNEQQ
ISIAYANYADGHADISQVVSFPFSVMLKTKEATEKRNIANFNDKEDVYLFVFSKCKSDNI
VQDSDLFFITKDGQYLLDTLNKVICASRQKQSSSDSTDDKG-ERFSPTALPSRPKPPGEP
GDYW--IEDNSDDESP----
>gi|654933801|ref|WP_028384145.1| hypothetical protein [Legionella moravica]
--------------------------------------------------------MNFK
ITQHY-ARGEEKLIAEFNELDEAKVFITKKSLTDEEERKKVIYRVYDDH-ELLIKLNKEN
LCVTHAKYAEGSADFHNS-ELIYHVFIKSIDSSERKEVAQFNDRNNARLFVFVIFETACE
LNESNLFLIFKN-NILIDTLNKNTIANQQG-ASGSSSNEKG-ATYRLSPLSTRPTPGGGP
ADYW--VEDKDDN-------
>gi|1590826518|ref|WP_131794978.1| hypothetical protein [Fluoribacter gormanii]
--------------------------------------------------------MRYI
ITEQF-ARGEENVIAEFSYLNDSHLFIAKKLAHTELEKQKIIFRLYDDS-DLLKEFNREN
ISVSHAKYAEGNGDL-NFVQLSFYVMIKTENEPEKKKIANFNDKDDANLFMVGKCESDET
LHDSDLLFLFKE-QNLMDTLNRTITIHRKKETTRFAGNEKG-TKFHPTPMPRRPTPPGGP
SDCW--IEEDEEHN------
>gi|966426119|ref|WP_058468657.1| hypothetical protein [Fluoribacter gormanii]
--------------------------------------------------------MRYI
ITEQF-ARGEENVIAEFSYLNDSHLFIAKKLAHTELEKQKIIFRLYDDS-DLLKEFNREN
ISVSHAKYAEGNGDL-NFVQLSFYVMIKTENEPEKKKIANFNDKDDANLFMVGKCESDET
LHDSDLLFLFKE-QNLMDTLNRTITIHRKNETTRFAGNEKG-TKFHPTPMPRRPTPPGGP
SDCW--IEEDEEHN------
>gi|1397616830|ref|WP_110143888.1| MULTISPECIES: hypothetical protein [Legionella]
--------------------------------------------------------MRYK
VTEQF-ARGEEKIIAEFSDLNDTHLFIAKKSAYTELEKQNIIFRLYDDS-DLLHEFNREH
ISVAYAKYAEGNGDL-NFVQFSFHVMIKTENTLEKTGIANFNDKNDANLFMVGKCETDKT
LLDSDLLFLFKE-QNLIDTLNRTITIHRKKETTRVTRNEKG-AKFHPTPMPRRPTPPGGP
SDCW--IEEDDENN------
>gi|966465816|ref|WP_058497177.1| hypothetical protein [Legionella drozanskii]
--------------------------------------------------------MHYK
ITEQF-ARGEEKPIAEFCELDDAQIFVTKKISNDEMQHKKIIYRLYDDS-QLLKKFNPEN
ISVGYARYAEEDLDFTNTILFLFNVMIQTGDSLERKNIANFNDENDANLFIIGKCDTDST
VHDNDLFCIFKG-KILMKNLNKRIIANQKIASEGSSANQSG-ATFRPTPIPTRPTPPGGP
SDCW--VEKDDDD-------
>gi|1085167954|gb|OGT57622.1| hypothetical protein A3F14_04795 [Gammaproteobacteria bacterium RIFCSPHIGHO2_12_FULL_43_28]
--------------------------------------------------------MLYK
VTKQY-LRGSETNCAEFSELKEAMNFVEAKVAEDASLNIKVIYRIHELG-EVIKEYDSTK
T-----------------------------------------------------------
-----------K-------AQPVSDQSAQDAAGMGAK-----SGFQPTPFNMAPRPGGTP
P-KW--LKDEED---DKEK-
>gi|1441208307|ref|WP_114834231.1| hypothetical protein [Aquicella lusitana]
MQIGTLVYPKMGCKNICIAHQCHFIAWDRWFIRTLAGFHFKQSIGSIARYQRSGVLMKYA
ITKQY-TRGPEASCAEFDDLNAARAYINEKLAEDFSLNIKITYRIYRTG-EMVEQFNPGN
P-----------------------------------------------------------
-----------M-------TS---SSGSQNEAGDSQGKEQT-ASFRPTPFNTTPRPPGTP
P-KW--IIDQEEDEKGKNK-
>gi|406915133|gb|EKD54246.1| hypothetical protein ACD_60C00105G0004 [uncultured bacterium]
--------------------------------------------------------MLYK
ITKQY-ARGTDIPVAEFNDMNDAKLFVSAKQEEDAKLRVKVTYRLFEGL-DLLQEFTESA
GS----------------------------------------------------------
-------------------------TSISSSGGGV--QQKS--SFQPTPFNNAPRPAGMP
H-SW--VKDDEKKESEK---
>gi|1085145663|gb|OGT36927.1| hypothetical protein A3F11_09115 [Gammaproteobacteria bacterium RIFCSPHIGHO2_12_FULL_37_14]
--------------------------------------------------------MFYQ
IKKQY-GRGVETIFAKFNDLSDAKLFIESKLAADAALNIKVIYRICEGI-DVIEEFHPEK
------------------------------------------------------------
-------------------NN---FASSSSSGS--QGQTST-ANFRPTPFNVAPRPTGTP
Q-KW--IKDDDEKDDETKK-
>gi|1085150201|gb|OGT41159.1| hypothetical protein A3F42_00760 [Gammaproteobacteria bacterium RIFCSPHIGHO2_12_FULL_37_34]
--------------------------------------------------------MLYQ
VKKQY-GRGSETIFAKFNDLTDANLFIKSKLAADLAVNEKVIYRIYEGV-DLVEEFNSES
------------------------------------------------------------
-------------------SN---LTAAQSSGSRSQSQASA-AGFRPTPFNATPRPTGTP
P-KW--VKENDEEE---KK-
>gi|1436124282|gb|RDI44555.1| hypothetical protein C8D86_10937 [Aquicella lusitana]
--------------------------------------------------------MKYA
ITKQY-TRGPEASCAEFDDLNAARAYINEKLAEDFSLNIKITYRIYRTG-EMVEQFNPGN
P-----------------------------------------------------------
-----------M-------TS---SSGSQNEAGDSQGKEQT-ASFRPTPFNTTPRPPGTP
P-KW--IIDQEEDEKGKNK-
>gi|406936745|gb|EKD70392.1| hypothetical protein ACD_46C00544G0004 [uncultured bacterium]
---------------------------------------------------------MYK
VTKQY-GRGSEIFAQSFSKLADATSFMQLAVEADAAMKVNVIYRLYEFD-EVIKEIDSSK
M-----------------------------------------------------------
-----------E-------L--AARENSQSGQGKTSG-----ATFKPTPFEMSPRPRSTP
P-KW--LHDEEDKNKDEDKK
>gi|1028420108|gb|OAI50022.1| hypothetical protein AYO45_00130 [Gammaproteobacteria bacterium SCGC AG-212-F23]
--------------------------------------------------------MYFK
VTKIYPGRNTETPMQDFAKEKDAIAFIQKSLAEDNHFSVTATYKLYEFS-DHIRTFSQAD
L-----------------------------------------------------------
-----------E-------QK---EGSSSSSSGSSSGRPGTSQTFSPTPFNTAPRPTGMP
H-SW--VKDDEDK-----KK
>gi|1085155535|gb|OGT45867.1| hypothetical protein A3E83_00625 [Gammaproteobacteria bacterium RIFCSPHIGHO2_12_FULL_41_20]
--------------------------------------------------------MRYK
VTEQY-VGGSDIPCAEFSKISDARLFVDNKLEADRRLKVRVTYRIYDGH-TVLEEKNQDS
LS----------------------------------------------------------
------------------------TTSTQTSSMQTTSTSSS-----PSPFSTTPKPAGMP
PSRWASVLKDEKEGKK----'`;

function printExample() {
    document.getElementById('demo').innerHTML = example;
    };

function print() {
    printExample();
}